services:
  # Tu aplicación de Python
  app-goles:
    build: .
    image: app-fase1:latest
    container_name: app-goles-container
    stdin_open: true # Permite la entrada de teclado
    tty: true        # Emula una terminal real
    networks:
      - jenkins-net

  # Servidor de Jenkins
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      # Esta línea es opcional pero recomendada si quieres que Jenkins 
      # pueda usar el Docker de tu máquina real:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net

networks:
  jenkins-net:
    driver: bridge

volumes:
  jenkins_data:
